spring:
  application:
    name: clinic-management

  # Configuración de base de datos SQL (H2 para desarrollo)
  datasource:
    url: jdbc:h2:mem:clinicdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # Configuración de JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # Configuración de H2 Console (solo para desarrollo)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuración de MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/clinic_management
      database: clinic_management

  # Configuración de seguridad
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Configuración del servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuración de logging
logging:
  level:
    com.mycompany.clinicmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuración de la aplicación
clinic:
  management:
    # Configuración de facturación
    billing:
      copay-amount: 50000
      annual-copay-limit: 1000000
      currency: COP

    # Configuración de validaciones
    validation:
      max-age: 150
      min-password-length: 8
      max-username-length: 15
      max-address-length: 30

    # Configuración de roles
    roles:
      recursos-humanos: "Recursos Humanos"
      personal-administrativo: "Personal Administrativo"
      enfermera: "Enfermera"
      medico: "Médico"
      soporte-informacion: "Soporte de Información"

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
